version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ./config/enabled_plugins:/etc/rabbitmq/enabled_plugins
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
  producer:
    build: 
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    restart: unless-stopped
    depends_on:
      - rabbitmq
  consumer:
    build: 
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    restart: unless-stopped
    depends_on:
      - rabbitmq
volumes:
  rabbitmq: